name = "maestro"
ard = ">= 0.30.0"

[dependencies]
decode = { git = "https://github.com/akonwi/ard-decode.git", commit = "e80c2d2" }
dram = { git = "https://github.com/akonwi/dram.git", commit = "025969f" }
sql = { git = "https://github.com/akonwi/ard-sql.git", commit = "56deab7" }