name = "maestro"
ard = ">= 0.37.0"

[dependencies]
decode = { git = "https://github.com/akonwi/ard-decode.git", commit = "c590f42ec43c5d362844925a8a978d64a1846c5c" }
dram = { git = "https://github.com/akonwi/dram.git", commit = "1fc5cdb24d10fc470a15b75c852255a92d18670e" }
sql = { git = "https://github.com/akonwi/ard-sql.git", commit = "4e0c13798c4ff0459ccb632b6edd9b8b07e5e6cb" }
