name = "maestro"
ard = ">= 0.38.0"

[dependencies]
decode = { git = "https://github.com/akonwi/ard-decode.git", commit = "c590f42ec43c5d362844925a8a978d64a1846c5c" }
dram = { git = "https://github.com/akonwi/dram.git", commit = "6e1809ccac7c5ed8c6aa3e91d9015f80bba48b1a" }
sql = { git = "https://github.com/akonwi/ard-sql.git", commit = "578f52d8f63d91532f31491a9125087519a8e128" }
