/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FixturesFixtureIdRouteImport } from './routes/fixtures.$fixtureId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesFixtureIdRoute = FixturesFixtureIdRouteImport.update({
  id: '/fixtures/$fixtureId',
  path: '/fixtures/$fixtureId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fixtures/$fixtureId': typeof FixturesFixtureIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fixtures/$fixtureId': typeof FixturesFixtureIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fixtures/$fixtureId': typeof FixturesFixtureIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fixtures/$fixtureId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fixtures/$fixtureId'
  id: '__root__' | '/' | '/fixtures/$fixtureId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FixturesFixtureIdRoute: typeof FixturesFixtureIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures/$fixtureId': {
      id: '/fixtures/$fixtureId'
      path: '/fixtures/$fixtureId'
      fullPath: '/fixtures/$fixtureId'
      preLoaderRoute: typeof FixturesFixtureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FixturesFixtureIdRoute: FixturesFixtureIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
